-- Access Overrides: per-user early unlocks for level groups, levels, and lessons

create table if not exists public.access_overrides (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  level_group_id bigint references public.level_groups(id) on delete cascade,
  level_id bigint references public.levels(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete cascade,
  note text,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamp with time zone default now() not null
);

-- Ensure at least one target column is set
create or replace function public.check_override_target()
returns trigger language plpgsql as $$
begin
  if NEW.level_group_id is null and NEW.level_id is null and NEW.lesson_id is null then
    raise exception 'One of level_group_id, level_id, or lesson_id must be provided';
  end if;
  return NEW;
end;
$$;

drop trigger if exists trg_check_override_target on public.access_overrides;
create trigger trg_check_override_target before insert or update on public.access_overrides
for each row execute function public.check_override_target();

-- Avoid duplicates per user/target
create unique index if not exists idx_unique_override on public.access_overrides (user_id, coalesce(level_group_id,0), coalesce(level_id,0), coalesce(lesson_id,0));

alter table public.access_overrides enable row level security;

-- Read for authenticated users (so the app can compute access)
drop policy if exists "access_overrides_read_all_auth" on public.access_overrides;
create policy "access_overrides_read_all_auth" on public.access_overrides
for select to authenticated using (true);

-- Only admins can modify
drop policy if exists "access_overrides_admin_write" on public.access_overrides;
create policy "access_overrides_admin_write" on public.access_overrides
for all to authenticated using (
  auth.uid() in (select id from public.users where role = 'admin')
) with check (
  auth.uid() in (select id from public.users where role = 'admin')
);


